### ISSUE TITLE
Error Getting Environment Set Up on Windows 10

### ISSUE THREAD

**Issue by H00plyha** [95anantsingh/NYU-SuperGAN#2]
Hello,

This looks like a very exciting piece of work and I am looking forward to giving it a whirl. However, when attempting to set up the environment using environment.yml in anaconda, I am running into an error. 

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - pyyaml==6.0=py38h0a891b7_4
  - brotlipy==0.7.0=py38h0a891b7_1004
  - nettle==3.6=he412f7d_0
  - argon2-cffi-bindings==21.2.0=py38h0a891b7_2
  - libwebp==1.2.2=h3452ae3_0
  - graphite2==1.3.13=h58526e2_1001
  - libdrm==2.4.109=h7f98852_0
  - cryptography==37.0.1=py38h9ce1e76_0
  - zeromq==4.3.4=h9c3ff4c_1
  - debugpy==1.6.0=py38hfa26641_0
  - pysocks==1.7.1=py38h578d9bd_5
  - ca-certificates==2021.10.8=ha878542_0
  - xorg-libsm==1.2.3=hd9c2040_1000
  - c-ares==1.18.1=h7f98852_0
  - libglib==2.70.2=h174f98d_4
  - numpy-base==1.21.5=py38hf524024_2
  - brotli-bin==1.0.9=h166bdaf_7
  - libgomp==11.2.0=h1d223b6_16
  - qt==5.12.9=h1304e3e_6
  - lame==3.100=h7f98852_1001
  - x265==3.5=h924138e_3
  - giflib==5.2.1=h36c2ea0_2
  - xorg-fixesproto==5.0=h7f98852_1002
  - xorg-libxext==1.3.4=h7f98852_1
  - xorg-libxi==1.7.10=h7f98852_0
  - jasper==2.0.33=ha77e612_0
  - ipykernel==6.13.0=py38h7f3c49e_0
  - xorg-libice==1.0.10=h7f98852_0
  - matplotlib-base==3.5.2=py38h826bfd8_0
  - dbus==1.13.6=h5008d03_3
  - xorg-xproto==7.0.31=h7f98852_1007
  - libopencv==4.5.5=py38h2380011_9
  - libblas==3.9.0=12_linux64_mkl
  - libbrotlidec==1.0.9=h166bdaf_7
  - importlib-metadata==4.11.3=py38h578d9bd_1
  - freeglut==3.2.2=h9c3ff4c_1
  - krb5==1.19.3=h08a2579_0
  - certifi==2021.10.8=py38h578d9bd_2
  - mkl-service==2.4.0=py38h95df7f1_0
  - terminado==0.13.3=py38h578d9bd_1
  - libogg==1.3.4=h7f98852_1
  - harfbuzz==4.2.0=h40b6f09_0
  - openjpeg==2.4.0=hb52868f_1
  - expat==2.4.8=h27087fc_0
  - libnsl==2.0.0=h7f98852_0
  - libsodium==1.0.18=h36c2ea0_1
  - keyutils==1.6.1=h166bdaf_0
  - intel-openmp==2021.4.0=h06a4308_3561
  - setuptools==62.1.0=py38h578d9bd_0
  - pandoc==2.18=ha770c72_0
  - libstdcxx-ng==11.2.0=he4da1e4_16
  - libtiff==4.3.0=h542a066_3
  - pyrsistent==0.18.1=py38h0a891b7_1
  - libprotobuf==3.20.1=h6239696_0
  - liblapacke==3.9.0=12_linux64_mkl
  - unicodedata2==14.0.0=py38h0a891b7_1
  - pytorch==1.10.2=py3.8_cuda11.3_cudnn8.2.0_0
  - widgetsnbextension==3.6.0=py38h578d9bd_0
  - xz==5.2.5=h516909a_1
  - aom==3.3.0=h27087fc_1
  - fontconfig==2.14.0=h8e229c2_0
  - libglu==9.0.0=he1b5a44_1001
  - libcblas==3.9.0=12_linux64_mkl
  - gst-plugins-base==1.20.2=hcf0ee16_0
  - jbig==2.1=h7f98852_2003
  - gmp==6.2.1=h58526e2_0
  - ncurses==6.3=h27087fc_1
  - cudatoolkit==11.3.1=h2bc3f7f_2
  - openssl==3.0.3=h166bdaf_0
  - libclang==13.0.1=default_hc23dcda_0
  - mistune==0.8.4=py38h497a2fe_1005
  - svt-av1==0.9.1=h27087fc_0
  - yaml==0.2.5=h7f98852_2
  - libxml2==2.9.12=h885dcf4_1
  - icu==69.1=h9c3ff4c_0
  - lcms2==2.12=hddcbb42_0
  - libdeflate==1.10=h7f98852_0
  - xorg-libxrender==0.9.10=h7f98852_1003
  - cffi==1.15.0=py38h3931269_0
  - libev==4.33=h516909a_1
  - libopus==1.3.1=h7f98852_1
  - libedit==3.1.20191231=he28a2e2_2
  - ipython==8.3.0=py38h578d9bd_0
  - tornado==6.1=py38h0a891b7_3
  - libpng==1.6.37=h21135ba_2
  - kiwisolver==1.4.2=py38h43d8883_1
  - _openmp_mutex==4.5=2_gnu
  - zstd==1.5.2=ha95c52a_0
  - pixman==0.40.0=h36c2ea0_0
  - libcurl==7.83.0=h2283fc2_0
  - alsa-lib==1.2.3.2=h166bdaf_0
  - mysql-common==8.0.29=h26416b9_0
  - libvpx==1.11.0=h9c3ff4c_3
  - libnghttp2==1.47.0=he49606f_0
  - mkl_random==1.2.2=py38h1abd341_0
  - markupsafe==2.1.1=py38h0a891b7_1
  - pyqtchart==5.12=py38h7400c14_8
  - libxcb==1.13=h7f98852_1004
  - libiconv==1.16=h516909a_0
  - gstreamer==1.20.2=hd4edc92_0
  - libssh2==1.10.0=ha35d2d1_2
  - libuv==1.43.0=h7f98852_0
  - libvorbis==1.3.7=h9c3ff4c_0
  - mysql-libs==8.0.29=hbc51c84_0
  - ffmpeg==4.4.1=hd7ab26d_2
  - cairo==1.16.0=ha12eb4b_1010
  - mkl_fft==1.3.1=py38h8666266_1
  - pyqt==5.12.3=py38h578d9bd_8
  - xorg-xextproto==7.3.0=h7f98852_1002
  - scipy==1.8.0=py38h56a6a73_1
  - xorg-libxdmcp==1.1.3=h7f98852_0
  - pthread-stubs==0.4=h36c2ea0_1001
  - py-opencv==4.5.5=py38h7f3c49e_9
  - lerc==3.0=h9c3ff4c_0
  - gnutls==3.6.13=h85f3911_1
  - libzlib==1.2.11=h166bdaf_1014
  - xorg-libxfixes==5.0.3=h7f98852_1004
  - sqlite==3.38.5=h4ff8645_0
  - liblapack==3.9.0=12_linux64_mkl
  - libwebp-base==1.2.2=h7f98852_1
  - libllvm13==13.0.1=hf817b99_2
  - xorg-libx11==1.7.2=h7f98852_0
  - jupyter_core==4.9.2=py38h578d9bd_0
  - libgfortran5==11.2.0=h5c6108e_16
  - xorg-kbproto==1.0.7=h7f98852_1002
  - gettext==0.19.8.1=h73d1719_1008
  - openh264==2.1.1=h780b84a_0
  - matplotlib==3.5.2=py38h578d9bd_0
  - xorg-libxau==1.0.9=h7f98852_0
  - psutil==5.9.0=py38h0a891b7_1
  - nss==3.77=h2350873_0
  - xorg-inputproto==2.3.2=h7f98852_1002
  - libevent==2.1.10=h28343ad_4
  - nspr==4.32=h9c3ff4c_1
  - zlib==1.2.11=h166bdaf_1014
  - libgcc-ng==11.2.0=h1d223b6_16
  - bzip2==1.0.8=h7f98852_4
  - ld_impl_linux-64==2.36.1=hea4e1c9_2
  - freetype==2.10.4=h0708190_1
  - hdf5==1.12.1=nompi_h4df4325_104
  - pyqt5-sip==4.19.18=py38h709712a_8
  - fonttools==4.33.3=py38h0a891b7_0
  - _libgcc_mutex==0.1=conda_forge
  - brotli==1.0.9=h166bdaf_7
  - jedi==0.18.1=py38h578d9bd_1
  - libpciaccess==0.16=h516909a_0
  - libpq==14.2=h676c864_0
  - pillow==9.1.0=py38h0ee0e06_2
  - tk==8.6.12=h27826a3_0
  - numpy==1.21.5=py38he7a7128_2
  - lz4-c==1.9.3=h9c3ff4c_1
  - python==3.8.13=ha86cf86_0_cpython
  - libva==2.14.0=h7f98852_0
  - mkl==2021.4.0=h06a4308_640
  - pyzmq==22.3.0=py38hfc09fa9_2
  - libuuid==2.32.1=h7f98852_1000
  - libffi==3.4.2=h7f98852_5
  - opencv==4.5.5=py38h578d9bd_9
  - libbrotlicommon==1.0.9=h166bdaf_7
  - libbrotlienc==1.0.9=h166bdaf_7
  - libgfortran-ng==11.2.0=h69a702a_16
  - pyqtwebengine==5.12.1=py38h7400c14_8
  - readline==8.1=h46c0cb4_0
  - xorg-renderproto==0.11.1=h7f98852_1002
  - libxkbcommon==1.0.3=he3ba5ed_0
  - pyqt-impl==5.12.3=py38h0ffb2e6_8
  - future==0.18.2=py38h578d9bd_5
  - jpeg==9e=h166bdaf_1
  - pcre==8.45=h9c3ff4c_0
  - x264==1!161.3030=h7f98852_1

Any and all assistance much welcomed!

**Comment by 95anantsingh** [comment]
This repo has Linux dependency, if you want to run it on windows the only way is WSL2, I recommend you follow this [guide](https://docs.nvidia.com/cuda/wsl-user-guide/index.html) to install. This should be followed by installing a suitable [conda](https://conda.io/projects/conda/en/latest/user-guide/install/linux.html) version on wsl distro.

**Comment by H00plyha** [comment]
Much appreciated! Will explore those options.
